### ISSUE TITLE
deployed on heroku but only tell me ok

### ISSUE THREAD

**Issue by branchmaster** [directlycrazy/Hyzen#1]
hi directlycrazy ,
I'm deployed my own version on heroku dyno :
https://hiezen.herokuapp.com/
but only tell me in response ok in content of app.
please help me how to use it on android.
waiting for your response
finest regards

**Comment by jamescolb7** [comment]
Thank you for taking an interest in this project.
At this current state of time, there is no homepage; although, there will be one in the near future.
To use Hyzen, you would need a direct link to a video/channel, or you can search using a search endpoint. (/search?q=<query>)
Regards.

**Comment by jamescolb7** [comment]
A trending / Homepage has been created.
